### PR TITLE
Sunxi current a20 dev3

### PR DESCRIPTION
**Pull request by navlrac**
(Third time lucky)
This pull adds:
- support for the Marsboard A20 version.
- code to power-on and keep the second A20 core in a wait loop.
- with secondary core in a wait loop, this allows a modified SMP boot protocol in Linux.
  - This is backwards compatible with existing Linux code.
  - TODO: update Linux to support it. This has been tested with a different (non-Linux) SMP kernel.
  - Secondary power-on is important for debugging - JTAG tools require all cores you wish to debug to be powered-on.

Improved, backwards compatible Linux sun7i SMP boot protocol:
- check if CPU1 is held in reset
- if in reset, normal power-on sequence
- if not in reset, set the cpucfg->BOOT_ADD register AND
- perform a "sev" OR a write of (2) to cpucfg->EVENT_IN register

Pull also includes some miscellaneous fixes:
- Add ELF loading support when networking is selected
- Make default sun7i prompts a little cleaner
- Remove ZFS filesystem config - It's not very common, if you really need it, I suggest adding it to the boards.cfg or edit .config manually
- minor typo fixes

### CODE REVIEW

**Comment by hno** [comment]
More nitpicking..

Startup secondary core on sun7i. Creates a new backwards compatible S…
https://github.com/navlrac/u-boot-sunxi/commit/95852416b2d4becec7b825f41908da4228ffbfe3

please use readl/writel for MMIO register access, not direct memory
reference via voilatile pointers. This applies for example to cpucfg->
references. volatile pointers do not really do the needed memory
barriers for ensuring the writes reaches hardware.

also, please update the existing github pull request instead of opening
new ones all the time, or even better use the linux=sunxi mailinglist
for patch review.

Regards
Henrik

ons 2013-08-14 klockan 04:30 -0700 skrev Carl van Schaik:

> (Third time lucky)
> This pull adds:
> 
> ```
>   * support for the Marsboard A20 version.
>   * code to power-on and keep the second A20 core in a wait loop.
>   * with secondary core in a wait loop, this allows a modified SMP
>     boot protocol in Linux. 
>           * This is backwards compatible with existing Linux code.
>           * TODO: update Linux to support it. This has been tested
>             with a different (non-Linux) SMP kernel.
>           * Secondary power-on is important for debugging - JTAG
>             tools require all cores you wish to debug to be
>             powered-on.
> ```
> 
> Improved, backwards compatible Linux sun7i SMP boot protocol:
> 
> ```
>   * check if CPU1 is held in reset
>   * if in reset, normal power-on sequence
>   * if not in reset, set the cpucfg->BOOT_ADD register AND
>   * perform a "sev" OR a write of (2) to cpucfg->EVENT_IN register
> ```
> 
> Pull also includes some miscellaneous fixes:
> 
> ```
>   * Add ELF loading support when networking is selected
>   * Make default sun7i prompts a little cleaner
>   * Remove ZFS filesystem config - It's not very common, if you
>     really need it, I suggest adding it to the boards.cfg or
>     edit .config manually
>   * minor typo fixes
> ```
> 
> ---
> 
> You can merge this Pull Request by running
>   git pull https://github.com/navlrac/u-boot-sunxi sunxi-current-a20-dev3
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/linux-sunxi/u-boot-sunxi/pull/46
> 
> Commit Summary
>       \* Fix typos
>       \* Add Marsboard-A20 board
>       \* Make default sunxi prompts a little cleaner.
>       \* Startup secondary core on sun7i. Creates a new backwards
>         compatible SMP boot protocol.
>       \* Enable ELF loading with network support.
>       \* Remove ZFS from default sunxi u-boot builds.
> File Changes
>       \* M arch/arm/cpu/armv7/sunxi/Makefile (7) 
>       \* M arch/arm/cpu/armv7/sunxi/board.c (2) 
>       \* A arch/arm/cpu/armv7/sunxi/postclk_init.c (36) 
>       \* A arch/arm/cpu/armv7/sunxi/secondary_init.S (48) 
>       \* A arch/arm/cpu/armv7/sunxi/smp.c (95) 
>       \* M arch/arm/include/asm/arch-sunxi/cpu.h (1) 
>       \* A arch/arm/include/asm/arch-sunxi/cpucfg.h (71) 
>       \* A arch/arm/include/asm/arch-sunxi/smp.h (38) 
>       \* M board/sunxi/Makefile (1) 
>       \* M boards.cfg (2) 
>       \* M include/configs/sun4i.h (2) 
>       \* M include/configs/sun5i.h (2) 
>       \* M include/configs/sun7i.h (8) 
>       \* M include/configs/sunxi-common.h (2) 
>       \* M tools/mksunxiboot.README (2) 
> Patch Links:
>       \* https://github.com/linux-sunxi/u-boot-sunxi/pull/46.patch
>       \* https://github.com/linux-sunxi/u-boot-sunxi/pull/46.diff

**Comment by navlrac** [comment]
I'll update the patch to use readl writel for consistency.

Don't incorrectly state that they are needed here to reach hardware. read the latest linux source, these macros compile out to volatile accesses with no memory barriers on ARM unless configured for bufferable DMA men, in which case the barrier is for the dma data, not the device write. The IO region itself is mapped strongly-ordered in u-boot, the strictest access class and certainly guaranteed to reach the device.

On the github usage, do I just push over the old head with my rebased work?

**Comment by hno** [comment]
Looks fine. Merged.

**Comment by jwrdegoede** [comment]
Carl, could youm perhaps also submit a fex file for the marsboard-a20 to the sunxi-boards repo ?

**Comment by navlrac** [comment]
I'm not running Linux yet. I've been busy with other kernels. Where would I get a fex file? Extract it from flash or possibly the Android SDK?

----- Original Message -----

**Comment by hno** [comment]
tor 2013-08-22 klockan 16:10 -0700 skrev Carl van Schaik:

> I'm not running Linux yet. I've been busy with other kernels. Where
> would I get a fex file? Extract it from flash or possibly the Android
> SDK? 

nanda partition in the flash is best source.

or if you have a full Android SDK for Marsboard A20 and this is what you
have flashed on the board and verified working then you can get the copy
you have in the SDK.

Regards
Henrik

**Pull request closed without merging**
