### PR TITLE
Added Marsboard-A10 to sunxi-current

### PR DESCRIPTION
**Pull request by Sweet-Peas**
This is the merged version of my Marsboard A10 support. 
/Pontus

### CODE REVIEW

**Comment by oliv3r** [comment]
Hi,

the mars board uses the exact same settings as the cubieboard, so you 
should use that instead.

**Comment by Sweet-Peas** [comment]
I know that but having u-boot printing Cubieboard on a Marsboard won't work for us. But if this is the consensus of the community we will be happy to keep a fork for our customers.

**Comment by oliv3r** [comment]
Ah, the naming issue. Well that whole bit will be overhauled in a few 
months time anyway, I have plans for it already, just need a bit of 
time. Then this will be moot ;)

In the meantime, I'll let Henrik decide whether to pull this or not, but 
I do hope that any other patches still head our way ;)

oliver

**Comment by jwrdegoede** [comment]
Hi,

Looking at the marsboard pictures at: www.marsboard.com I don't see an axp (axp209) on there, so the boards.cfg line should end with: "sun4i:MARSBOARD_A10,SPL,SUNXI_EMAC,NO_AXP

Which would also make it distinct from the cubieboard.

Regards,

Hans

p.s.

Also a correct fex file for the marsboard would be a welcome addition to the sunxi-boards repository.

**Comment by oliv3r** [comment]
nice catch hansg,
also talked to hno and I was missinformed about the duplicate dram 
entries. If you can submit a fixed version, i'll gladly merge it

**Comment by Sweet-Peas** [comment]
I'll get that fixed tomorrow morning.

**Comment by hno** [comment]
"stock firmware" means a known well working livesuit image designed for the exact board used.

**Comment by blunden** [comment]
hno: Right. Problem is that the board won't boot fully. It should supposedly already have been flashed with an Android build from the factory and 4 leds are suppose to light up when it has booted. Currently using a Nexus 7 charger to power it but maybe that's too weak, even though its rated output is 2A according to ASUS. A20 boards are power hungry I hear.

Anyway, my problems are unrelated to this change and I should avoid taking the comments too far off topic. Sorry about that.

**Comment by oliv3r** [comment]
This should be mergeable now, it's a distinct board and should be correct now. Will merge this (or anybody else) if there are no other comments in the next few days.

**Comment by WebReflection** [comment]
shouldn't this go directly in the general boards folder too so it's possible to `./configure MarsBoard` too ?
I am talking about [this folder](https://github.com/linux-sunxi/sunxi-boards/tree/master/sys_config/a10).
Thanks

**Comment by hno** [comment]
Hmm..  confused. What is the difference between Marsboard A10 and Marsboard A10 1GB?

There is a 1GB Marsboard-A10 in sunxi-current. Please verify and if anything more is needed submit a new request.

**Pull request closed without merging**
