### PR TITLE
Added support for Marsboard 1GB

### PR DESCRIPTION
**Pull request by Sweet-Peas**
It would be great to have this board supported directly.
Thanks
/Pontus

### CODE REVIEW

**Comment by hno** [comment]
Please rebase this to the sunxi-current branch.

lör 2013-06-08 klockan 04:10 -0700 skrev Sweet-Peas:

> It would be great to have this board supported directly.
> Thanks
> /Pontus
> 
> ---
> 
> You can merge this Pull Request by running
>   git pull https://github.com/Sweet-Peas/u-boot-sunxi sunxi
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/linux-sunxi/u-boot-sunxi/pull/38
> 
> Commit Summary
>       \* Added support for Marsboard 1GB
> File Changes
>       \* A board/allwinner/marsboard/Makefile (50) 
>       \* A board/allwinner/marsboard/board.c (35) 
>       \* A board/allwinner/marsboard/dram.c (31) 
>       \* M boards.cfg (1) 
> Patch Links:
>       \* https://github.com/linux-sunxi/u-boot-sunxi/pull/38.patch
>       \* https://github.com/linux-sunxi/u-boot-sunxi/pull/38.diff

**Comment by oliv3r** [comment]
This should get merged with your other request in the next few days.

**Comment by hno** [comment]
Can't see this merged... ???

**Comment by hno** [comment]
This got lost somewhere, and meanwhile partially merged from another submission. LED support is missing however. Please rebase and resubmit.

**Pull request closed without merging**
