### PR TITLE
Lichee dev minor fixes

### PR DESCRIPTION
**Pull request by hramrach**

### CODE REVIEW

**Comment by hno** [comment]
The cross-compile check change is wrong. That part is for native builds where it should not be set.

**Comment by hno** [comment]
kernel arguments change had been merged. The cross-compile check change rejected.

**Comment by hramrach** [comment]
No, the check as is in the lychee-dev branch is wrong ( and different from the main branch).

The change in this pull request fixes the requirement that you set CROSS_COMPILE= (empty) manually on native builds.

**Comment by hno** [comment]
tis 2013-02-12 klockan 08:14 -0800 skrev hramrach:

> No, the check as is in the lychee-dev branch is wrong ( and different
> from the main branch).
> 
> The change in this pull request fixes the requirement that you set
> CROSS_COMPILE= (empty) manually on native builds. 

Then send a separate pull request for that change and I'll review it
again.

Regards
Henrik

**Pull request closed without merging**
