### PR TITLE
add iteaduino_plus_a10 and iteaduino_plus_a20 support

### PR DESCRIPTION
**Pull request by iteadsw**
We add iteaduino_plus_a10 and iteaduino_plus_a20 support. See me commit.

### CODE REVIEW

**Comment by jwrdegoede** [comment]
Hi,

As I already said in your previous pull-req:

Please use the dram_cubieboard.c and dram_cubieboard2.c files for the dram settings, rather then adding new ones. The settings for the iteaduino are identical to those of the cubieboard 1 / 2.

Thanks,

Hans

**Comment by iteadsw** [comment]
This is we commit.Delete dram iteada10.c and iteada20.c

**Comment by iteadsw** [comment]
hi,do you check our u-boot-sunxi file?Are there any question?

**Comment by oliv3r** [comment]
Can you merge commit  all 3 commits into one? That should be easily merge-able then :)

**Comment by iteadsw** [comment]
We provide two documents for two boards.

**Comment by oliv3r** [comment]
Yes you do, but you pushing 3 patches that add stuff, delete stuff etc. Squash those 3 patches in 1 (and if you are going for A+ ;) split them to 1 patch per board, but that's not required).

to squash those patches, look at git rebase -i HEAD~5 and use 'fixup' to squash the patches involved, so probably you'd use 2 fixups ontop of your main patch.

**Comment by hno** [comment]
Merged.

**Pull request closed without merging**
